export const REQUEST_GEO_COORDS = 'REQUEST_GEO_COORDS';
export const REQUEST_GEO_COORDS_ERROR = 'REQUEST_GEO_COORDS_ERROR';
export const RECEIVE_GEO_COORDS = 'RECEIVE_GEO_COORDS';

export const REQUEST_WEEDMAPS_LISTINGS = 'REQUEST_WEEDMAPS_LISTINGS';
export const REQUEST_WEEDMAPS_LISTINGS_ERROR = 'REQUEST_WEEDMAPS_LISTINGS_ERROR';
export const RECEIVE_WEEDMAPS_LISTINGS = 'RECEIVE_WEEDMAPS_LISTINGS';

export const REQUEST_WEEDMAPS_LISTING_DETAILS = 'REQUEST_WEEDMAPS_LISTING_DETAILS';
export const REQUEST_WEEDMAPS_LISTING_DETAILS_ERROR = 'REQUEST_WEEDMAPS_LISTING_DETAILS_ERROR';
export const RECEIVE_WEEDMAPS_LISTING_DETAILS = 'RECEIVE_WEEDMAPS_LISTING_DETAILS';
